# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
