# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170115_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='alarm',
            name='video_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.URLBank'),
        ),
    ]
