# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170119_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URLBank',
            new_name='Video',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='video_url',
            new_name='video',
        ),
    ]
